### ISSUE TITLE
Реализовать возможность подтягивать оценки в score напрямую из PR

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#10]
Варианты:
- Chrome extension 
- GitHub web hooks
- ????

**Comment by davojta** [comment]
Ооо экстеншен я напишу )

**Comment by davojta** [comment]
Только надо с форматом оценки определится )

**Comment by davojta** [comment]
С экстеншном у меня давно идеи бродят, тк там много чего можно делать )
