### ISSUE TITLE
Использование beta.2 версии гайда для именование коммитов

### ISSUE THREAD

**Issue by aplatkouski** [rolling-scopes-school/docs#142]
Вопрос: использование beta-версии является осознанным выбором или "неактуализированной" ссылкой?

См. документ [git-convention.md][]
```
## Требования к именам коммитов
- Названия коммитов должны быть согласно [гайдлайну](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
```

[git-convention.md]: https://github.com/rolling-scopes-school/docs/blob/master/docs/git-convention.md

**Comment by dzmitry-varabei** [comment]
@aplatkouski спасибо! ссылку исправил!
