### ISSUE TITLE
Обновить ссылку на пример задания.

### ISSUE THREAD

**Issue by NiyazGaripov** [rolling-scopes-school/docs#144]
В первом пункте раздела [Алгоритмические задания](https://docs.rs.school/#/stage1?id=%d0%90%d0%bb%d0%b3%d0%be%d1%80%d0%b8%d1%82%d0%bc%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b5-%d0%b7%d0%b0%d0%b4%d0%b0%d0%bd%d0%b8%d1%8f) имеется [ссылка](https://github.com/siarhei-smantsar/love-triangle) на пример задания. При переходе по данной ссылке выполняется переход на 404 страницу. 
Так как сам не нашёл корректную ссылку, то решил создать issue. Подскажите пожалуйста корректную ссылку, либо критерии по которым нужно найти подходящие примеры и заменить ссылку.

**Comment by dzmitry-varabei** [comment]
Привет! Спасибо за issue
Можешь добавить ссылку на https://github.com/AlreadyBored/basic-js
