### ISSUE TITLE
Инструкция по деплою

### ISSUE THREAD

**Issue by abadire** [rolling-scopes-school/docs#149]
По [ссылке](https://docs.rs.school/#/stage2?id=%d0%9a%d0%b0%d0%ba-%d1%81%d0%b4%d0%b5%d0%bb%d0%b0%d1%82%d1%8c-%d0%b4%d0%b5%d0%bf%d0%bb%d0%be%d0%b9-%d0%b7%d0%b0%d0%b4%d0%b0%d0%bd%d0%b8%d1%8f-%d0%b8%d0%b7-%d0%bf%d1%80%d0%b8%d0%b2%d0%b0%d1%82%d0%bd%d0%be%d0%b3%d0%be-%d1%80%d0%b5%d0%bf%d0%be%d0%b7%d0%b8%d1%82%d0%be%d1%80%d0%b8%d1%8f-%d1%88%d0%ba%d0%be%d0%bb%d1%8b) инструкция по деплою из приватного репозитория школы. В первом пункте идёт речь о создании ветки gh-pages, что навело меня (и не только меня) на неверную мысль, что с этой веткой можно творить что угодно) После её удаления и пересоздания в моей репо сбились настройки Github Pages, после чего я не мог задеплоить проект.

Предлагаю изменить пункт 1 этого раздела.

**Comment by dzmitry-varabei** [comment]
@abadire отличное замечание! удалил этот пункт! спасибо!
