### ISSUE TITLE
Этап самоподготовки перед стартом основного JS/FE курса 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#150]
![image](https://user-images.githubusercontent.com/2429680/95008273-a6104d00-0618-11eb-9bdf-9cc4c354aa8c.png)
![image](https://user-images.githubusercontent.com/2429680/95008277-b6282c80-0618-11eb-9ea6-98c1061a36f1.png)

**Comment by Viklysx** [comment]
На странице с материалами неоднозначно указано про PP, а именно сначала написано, что он не требуется, но при этом указано про ошибки и штрафы за несоответствие PP:

![image](https://user-images.githubusercontent.com/58310634/99715772-57c7e800-2ab8-11eb-84fb-a5929fa9f52e.png)

**Comment by irinainina** [comment]
Спасибо. Речь о том, что полное совпадение с макетом не требуется. Дальше речь о том, что могут быть отступы в 5-10 рх. Это довольно много. Но если вопрос возник, исправлю.
