### ISSUE TITLE
Дизайн макета для 2021Q1

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#155]
Новый макет для замены singolo/shelter.
Тематика: природа, экология.

![image](https://user-images.githubusercontent.com/2429680/95717233-ee5cea00-0c6c-11eb-81b5-42d3aac077f9.png)

**Comment by dzmitry-varabei** [comment]
@macroG0D Пиши, как будут новости. спасибо!

**Comment by macroG0D** [comment]
@dzmitry-varabei Обсудили основные детали с @sergeyshalyapin. Ожидаю ТЗ которое при первой возможности передам в работу своим дизайнерам.

**Comment by macroG0D** [comment]
@dzmitry-varabei
Что-ж, готовы дизайн макеты для заданий фронтенд курса RSS!!! 😊 

Вместе с @sergeyshalyapin подготовили техническое задание: https://docs.google.com/document/d/1xiuYgyDOavCJ0Z66g8xf37iVqrI0aC-JnC-OAwxFOsw/edit

В течении последнего месяца мои ученики работали над этим заданием в качестве своего курсового проекта по дизайну.
Получилось 9 работ. Почти все на достаточно высоком уровне и можно выбрать как одну из работ, так и все понравившиеся. И выдавать их на предстоящих потоках front-end курса в качестве заданий (например, вместо shelter). Таким образом можно на разных потоках давать разные варианты чтобы было разнообразие для студентов, идущих на второй-третий круг.

Вот список выполненных работ:
https://docs.google.com/spreadsheets/d/1vkRWfiDtWQ3wO_bHPuI4oGYT8eP30024Ad01jT1JtO4/edit?usp=sharing

Хочу обратить внимание на то, что у некоторых проектов дизайн распределен на несколько страниц в фигме — например, главная страница, внутренние страницы, адаптивы, компоненты — могут быть разделены на соответствующие разделы в фигме. Поэтому, если вдруг, кажется, что в дизайне не хватает каких-то страниц, скорее всего они просто в соседнем разделе (разделы проекта расположены в левом верхнем углу фигмы).

Я буду благодарен за какой либо фидбек по качеству работ и если какие-то из проектов понравятся больше остальных, тоже буду рад такой информации чтобы передать ее авторам — им будет приятно и полезно.

Кроме того, я обещал своим студентам, что если их работы будут выбраны, они смогут прикрепить к своему дизайн портфолио, ссылку на качественно сверстанный по их дизайну сайт. Поэтому, тегайте меня пожалуйста на будущие таски по этим проектам, чтобы я мог сдержать свое слово 🙂

Также, в футере всех выполненных проектов есть логотипы RSS и моей школы YemDigital — подразумевается, что ссылка на лого Rolling Scopes будет вести на сайт front-end курса, а ссылка на мое лого, будет вести на сайт моей школы (https://academy.yem.digital/)

Мне кажется, это очень крутая коллаборация и через какое-то время (когда у меня созреют новые выпускники), можно будет повторить 😊

Если что, я всегда на связи в телеграме (https://t.me/tonyem) и дискорде (TonyYem#4672).
Очень жду обратную связь )
