### ISSUE TITLE
План менторинга в 2020Q3.

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#157]
Ниже примерное расписание и план менторинга в stage#2 2020Q3. 
Буду рад вашим идеям на тему "как потратить время ментора наиболее эффективно".

План менторинга необходим, чтобы студенты и менторы знали как построить свое общение.

Актуальная версия плана тут -
https://github.com/rolling-scopes-school/mentoring/blob/master/JS-FE-2020Q3/mentoring-plan.md

### Изменения в RS APP 
Изменения направлены на создание более благоприятных условий студентам обучающимся без менторов.

1. Изменение веса оценок
      - Коэффициент для cross-check 0.8
      - Коэффициент менторской оценки 0.2

2. Две системы рейтинга студентов в Score.
      - Обычная (как сейчас)
      - Чисто по cross-check (его учитывать при выдаче сертификатов школы)

3. Изменения в расписании
 - Дедлайны заданий по понедельникам
 - Дедлайны указаны в формате UTC , а не GMT+3
 - Кросс-чеки стартуют на следующий день после дедлайна

**Comment by Pulya10c** [comment]
1.Каждому ментору создать документ(например в гугл доке), в который студенты ьбудут писать свои текущие вопросы. Все вопросы нужно разбирать на еженедельной встрече со студентами.
2.Ввести дедлайны проверки заданий менторами. Лучших менторов, которые все делали в срок, делали качественное ревью, встречались регулярно со студентами - поощрять дополнительными подарками.
3.Рассмотреть возможность лишения студента ментора за недобросовестную учебу или нарушение правил школы. Лучше ментор будет помогать тому студенту, который делает все в срок, хочет учиться и не нарушает установленные правила обучения, чем помогатьстуденту,который забивает на учебу.

**Comment by dzmitry-varabei** [comment]
Примеры code review от Andrei Markovich

1) успевающего студента:
- https://github.com/rolling-scopes-school/arzamas-ka-RS2020Q1/pull/1
- https://github.com/rolling-scopes-school/arzamas-ka-RS2020Q1/pull/5

2) не очень успевающего:
- https://github.com/rolling-scopes-school/kastrubait-RS2020Q1/pull/5

3) другие:
- https://github.com/rolling-scopes-school/matusvit-RS2020Q1/pull/4
- https://github.com/rolling-scopes-school/dmitriyfriz-RS2020Q1/pull/4

**Comment by dzmitry-varabei** [comment]
# Краткие рекомендации по проверке работ студентов Rolling Scopes School от  Andrei Markovich

Данные рекомендации основаны на личном опыте, приктикам и style guides, которые используются на проекте и преследует цель помочь студентам понять основные ошибки/плохие практики/неточности, которые лучше избегать.

Проверку пулл реквеста можно начать с проверки корректности оформления реквеста, именования коммитов и достаточного их количества.
[Требования к коммитам](https://docs.rs.school/#/git-convention)
[Требования к pull request](https://docs.rs.school/#/stage2?id=%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-pull-request-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%BE-%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%82%D1%8C-%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D1%8E%D1%89%D1%83%D1%8E-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8E)

Далее можно склонировать репозиторий, установить завимсимости и проверить собирается ли проект. Если в требованиях было использования линтера или тестов проверить наличие прописанного скрипта для запуска (lint, test), возникают ли ошибки после запуска. Так же стоит обратить внимание есть ли в коде места, где выключены правила линта и попытаться выяснить для чего это было сделано и можно было ли этого избежать.

Стоит проверить общую функциональность приложения, отсутствуют ли ошибки в консоли, корректно ли отрабатывают запросы и т.д.

На этом этапе можно обратить внимание на возможные UI/UX проблемы:

- выделяются ли кликабельные элементы

- не происходит ли перекрытие элементов/текста

- возможно найдутся рекомендации по улучшению внешнего вида если четко заданного дизайна в задании не было

Далее code review.

Возможные моменты, где можно улучшить качество кода:

**Общие принципы**

- DRY - если есть повторяющиеся куски кода, лучше выносить их в отдельный класс/функцию

- KISS - пытаться сохранить простую и понятную структуру
- комментарии стоит оставлять для объяснение задачи кода, а не для его описания

```
Bad

# method to find min value
function findMinValue() {...}
```

- не использован форматтер кода, они помогают привести код к одному стилю для всех членов команды (e.g. prettier)
- лучше для именования переменных/классов/функций не использовать сокращения, это улучшит понимание и читабельность кода

**HTML**

- отсутствие атрибута alt для тeга img, так же рекомендуется проставлять высоту и ширину, это полезно когда картинка по какой-то причине не подгрузится
- отсутствие или недостаточная семантика
- избыточные блоки

```html
<div class="container">
  <div class="wrapper">
    <ul>
      ...
    </ul>
  </div>
</div>
```

- для html использовать имена классов в kebab-case

```html
<!-- BAD -->
<div class="containerWrapper"></div>
```

```html
<!-- GOOD -->
<div class="container-wrapper"></div>
```

- если в html нужно сделать какой-то заголовок в upper case лучше это делать стилем

**CSS**

- динамические стили стараться применять классами а не js
- стараться писать стили с небольшой степенью вложенности (не больше 2х) - это упрощает сопровождение и переопределение стиля при необходимости
- предпочтительнее использовать одни единицы измерения (или px или rem или em) это позволит проще вносить изменения(при использовании препроцессоров можно написать функцию которая будет переводить пиксели в рем)

**JS**

- использовать event delegation, если его можно использовать
- для блоков if else for использовать скобки
- magic numbers and magic strings - стараться выносить их в отдельные константы
- использовать объекты enums

```js
const KEY_CODES = {
	Space: 32,
	Enter: 13,
	...
}

if (key === KEY_CODES.Enter) {
  ...
}
```

- размер файлов (большие файлы трудно читать и поддерживать, если файл больше 200 - 400 строк, то следует задуматься о разделении)
- следить за степенью вложенности условных блоков, блоки со степенью вложенности 3 и более трудно читать и воспринимать, возможно их можно вынести в отдельную функцию
- стараться использовать чистые функции (они лучше тестируются)
- использовать named arguments если число аргументов 3 и более, это позволяет не следить за порядком и при чтении кода более понятно что передается в функцию

```js
function insertElement({ parent, tag, class, value }){...}

insertElement({ parent: parentElement, tag: 'p', class: 'class', value: 'Some value' })
```

**Comment by humanamburu** [comment]
## Рекомендации по организации проверки задания

Для более эффективного процесса код ревью заданий студентов, я бы порекомендовал практику декопозиции кода задания, как миниум на две части:
- **Draft**
Минимальная версия, которая показывает основную концепцию задачи и реализует основные части приложения в виде MVP. Решенная таким образом задача может не покрывать дополнительные требования.
- **Release**
Законченная и отрефакторенная версия, в которой испрвлены замечания по фундаментальному подходу и учтены пожелания во время ревью Draft версии.

Такой подход решает несколько проблем, которые встречаются при ревью и разработке больших заданий:
-  Снижение единовременноой ревью нагрузки на ментора. 
Зачастую довольно сложно внимательно посмотреть весь код задания за один раз и разъяснить все концепты, которые пропустил студент в рамках большой код базы. Зачастую гораздо проще найти время на 2 ревью поменьше, хотя в целом суммарно времени может уйти больше.
- Архитектурные промахи в самом начале, которые влекут за собой "дорогие" в плане рефакторинга проблемы
- Обучение работы с Git и Github
- Мотивация успеть в дедлайн

Рекомендую ставить промежуточные дедлайны на большие задания, в рамках которых проводить ревью Draft версии задачи без снижения финальной оценки.
