### ISSUE TITLE
Переход от отдельных md файлов к структурированной документации

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#17]
Предлагаю реализовать "документацию в виде сайта" на базе текущего набора md файлов.
Пример, как должен выглядеть результат - https://lodash.com/docs/4.17.11

Основные фичи:
1) Вся документация выглядит как единый файл
2) Можно перейти к конкретному разделу (Например, https://lodash.com/docs/4.17.11#noop)
3) Версионирование документации
4) Консистентный перевод (все переводы представляют одну версию документации)
5) Глоссарий терминов RSSchool
6) ...
 
Что забыл? 
Какие варианты по тех-стеку для реализации?

**Comment by dimadk24** [comment]
Предлагаю реализовать с помощью [gitbook](https://www.gitbook.com). Сам не работал, но видел, что многие доки open source проектом используют их. Поддерживают Markdown, синкаются с гитхабом, бесплатны для open source проектов

**Comment by davojta** [comment]
Доки можно было бы вести как гитбук. Можно сделать таску вместо ментор дашборда про документацию, поиск на фреймворке например )
