### ISSUE TITLE
Пересмотр оценки, в случае если студент исправил замечания

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#18]
Собираю предложения, что необходимо сделать ментору, если студент исправил замечания? 

1) Что должен делать студент с замечаниями ментора?
2) Можно ли пересмотреть оценку, если студент исправил замечания
3) Что делать если студент исправил, например, ошибки eslint? вкомитал функционал, который не был реализован к дедлайну?
4) ...

**Comment by davojta** [comment]
Я студентов так оценивал
1) просил чтобы делали задания до дедлайна, чтобы было время чекнуть
2) проверял до дедлайна - и оставлял замечания, они исправляли
3) если чтото было не так, я снижал оценку (это менторское снижение - за плохой код и тд, а не за функциональность) - и говорил что не буду снижать, если исправят за какой то короткий промежуток времени (eslint, refactorings, etc)
4) если у студента проект готов, но не запускаются, какие то косяки на моем компе - то тоже не снижал, если исправляют (и снижал)
5) функциональность вкоммитанную после дедлайна студенты оценивали отдельно и делали скидку на сдачу после дедлайна. Студенты еще и предупреждали.

Обычно времени исправлять \ доделыть есть только у сильно успевающих студентов. Большиство еле еле успевают к деддлайну - 3- 5 дней после.

**Comment by AliaksandrZahorski** [comment]
Процесс обучения включает в себя как образовательные, так и воспитательные задачи. То, что для одного студента будет положительным воздействием и поможет в развитии навыков - для другого может стать разочарованием. Правильно использовать инструменты оценок - этому тоже необходимо учить.
Как уже писал ранее, у большинства менторов таких навыков и педагогического опыта нет, что приводит к необходимости загонять учебный процесс в жесткие рамки. Логично идти по пути дальнейшего упроцения процессов оценок, доведя систему до зачетной, т.е. сдал/не сдал. Это же позволит ускорить обработку результатов оценивания, например в виде таблицы студентов с ячейками отметок (+/-).

**Comment by dzmitry-varabei** [comment]
Если сделать так:
1) Фичи сделал до дедлайна и все идеально - за них можно получить 100% баллов
2) Фичи, которые сделал или доделал после дедлайна получают штраф -30%
3) Пока фича не доделана полностью - 0 баллов

**Comment by mrstalon** [comment]
Надо только определится с временем, которое будет у студента на доработку

**Comment by Sijioth** [comment]
В этом есть смысл, так как у всех скорость усвоения информации разнится. Кроме того, база также играет достаточно большую роль.
А так будет дополнительная мотивация доделать-таки таску до конца)

----
По времени на доработку: предлагаю до дедлайна следующей таски.
Аргументы за: 
достаточно либерально и должно отсеять споры за "много-мало" времени, к тому же отпадает необходимость оценивать доп. время для каждой таски.

Аргументы против:
у некоторых студентов может сложиться тенденция хронически допиливать фичи после дедлайна.

Однако, это все же не столь критично, имхо, и в целом считаю саму идею годной к воплощению.

**Comment by davojta** [comment]
@AliaksandrZahorski мне нравится идея с бинарным сделал \ не сделал, хотел даже чекбоксы замутить в задании на Дом Код Джем - но у меня такое смутило
- много переделывать в заданиях надо. Много переделывать - много потом вопросов у студентов
- для меня фича - это 50% + 1, я считаю что она сделана но с дисконтом.
- мне не сложно считать, если студент делает самопроверку + нормальное не усложненое условие задачи

**Comment by davojta** [comment]
@AliaksandrZahorski 

> большинства менторов таких навыков и педагогического опыта нет, что приводит к необходимости загонять учебный процесс в жесткие рамки

Менторы на курсах тоже учаться (быть менторами, наставниками, помогать людям,у которых меньше знаний \ навыков).

Это не педагогика в чистом виде, не воспитание - это профессиональное обучение основам специализации. Да есть моменты с дедлайном, менторами, еще чем то. 

Да и .в целом определенная нечеткость курсов - она как фишка. Тк дает тебе хорошо понять, что ТЗ - это основа эффективной работы.

**Comment by davojta** [comment]
@dzmitry-varabei у нас есть проблема с определением что такое фича )

И я не вижу чем логика стандартного дисконта к оценке хуже - типо -10%, - 30% и -70%

Я -70% применял когда студент хочет доделать \ передалать задания чтобы дотянуться до сертификата.

**Comment by davojta** [comment]
Я насчет таблиц с оценками - обсуждали после набора 2018q3 систему
- базовое задание 
- нормальное задание
- повышенной сложности 

На каждый по 2-4 пункта, по 10 баллов за каждый
Там понятно как оценивать частично сделанное \ или не сделанное.

Понятно к чему можно привязываться при выдачи сертификата (нормальное задание на 80 процентов)

Понятно студенту, как получить сертификат.

**Comment by Sijioth** [comment]
> есть проблема с определением что такое фича )

@davojta 
Имхо, фичей можно считать (в рамках отдельно взятой таски) одно из требований, которое оценивается баллами.
Вот у тебя в задании кодДжема четко этот момент прослеживается.

**Comment by auseika** [comment]
1. Фіксіць. Нават калі студэнт выканае патрабаванне даволі фармальна, каб дабраць балы, ў галаве трабл адкладзецца, і, потым, спадзяюся, вырашыцца. Калі проста прастаўляць адзнаку і пісаць заўвагі, якія студэнт праглядзіць адзін раз і забудзецца, эфект будзе не такі добры.
2. Абавязкова, інакш не будзе матывацыі каб фіксіць.
3.  Схема, калі юзаюцца штрафы за пратэрміноўку - ок, таму што за першыя 3 дні здымаецца 10 балаў, а не нейкі % ад агульнага скора, т.б. практычна ў любым выпадку калі ўкласціся з фіксамі ў гэтыя 3 дні пасля дэдлайну, па выніку застанешся ў плюсе. Хаця канешне, трэба матываваць людзей на здачу як мінімум за пару дзён да deadline, каб яны вучыліся спакойна працаваць, а не гарэць ў апошнюю ноч. Бонусы ўвесці за падобнае?..

**Comment by Shastel** [comment]
2. Я считаю, что правильно не ставить оценку, пока ошибки не исправлены == функционал не вмержен.

**Comment by cathzetjo** [comment]
Не всегда ясен **итоговый балл**, выставленный ментором. На этом акцентируют внимание многие студенты.  Есть обязательства у студентов по оформлению PR. Предлагаю сделать такое же требование для менторов. 
Например итоговый коммент ментора должен выглядеть кроме рекомендаций с вот таким дополнительным расчётом:
Total: 100-10-5-10= 75
-10 опоздание сдачи таска на 1 день
-5 неверное название классов
-5 неверное определение заголовка h1
-10 несоблюдение требования по eslint.
По поводу **доработок** тасков - это важно. Ибо то, что студент не успел, это чаще всего то, что было самое сложное для него. И важно дожать этот момент. Оценка за доработку может быть с  коэффициентом. Например изначально +10 баллов за доработку и -10 если ее не сдашь вообще. Чем позже  сдашь доработку, тем ниже коэффициент пересчета. Через сутки после коммента ментора + 10 баллов , через 48 часов + 9 и т.д. Через 10 дней доработки больше не принимаются и снимается дополнительно -10 баллов. В общем скоре делать отдельную колонку по доработкам.
Согласна с Костей про введение бонусов за сдачу таска **до дедлайна**. +10 баллов за каждый день например. Даже если человек не успеет раньше, то будет стремиться к этому и в итоге эффект будет положительный. Тоже учитывать это в отдельной колонке.

**Comment by JuliaMV** [comment]
Я думаю это хорошая идея как-то мотивировать студентов за исправление замечаний менторов и доделывание фич, и было бы неплохо давать баллы, но не большие, с каким-то коэффициентом. Но в то же время это дополнительная нагрузка на менторов, к сожалению и так далеко не все менторы успевают проверить таски студентов в течение двух недель после сдачи, будет ли у них возможность/желание просматривать таски ещё раз? одно дело если студент поправит magic numbers, и совсем другое, если сделает несколько фич, попутно переделав всю логику.

**Comment by daniil-loban** [comment]
Что необходимо сделать ментору, если студент исправил замечания?

: Если студент быстро исправил замечания, потери по баллам должны быть минимальны (все таки это учеба) к тому же вероятно есть мотивация у студента.
Если долго исправлял или не проявил желания или нашел отговорки, оценка на усмотрение ментора (насколько критична ошибка, насколько критична реакция студента)

Что должен делать студент с замечаниями ментора?

: Студент должен услышать и понять замечания ментора, они не беспочвены а исходят из опыта ментора, возможно попросить у ментора (если есть время) дополнительное небольшое задание для закрепления и подтверждения того что знания закреплены ошибка не повториться, уточнить у ментора чем именно плоха какая-то ошибка
общение всегда хорошо. Возможно что-то не сделано из-за нехватки времени, а возможно из-за неумения им распоряжаться поэтому тут важна беседа, но не слишком долгая.

Можно ли пересмотреть оценку, если студент исправил замечания?

: Пересмотреть оценку можно, но так как цель учеба лучше дать шанс реванша в виде дополнительных индивидуальных пунктов в следующем таске - на мой взгляд это очень спортивно, нужно принимать неудачи, но и нужно стремиться к успеху, а не ждать шанса что все как-то уляжеться. 


Что делать если студент исправил, например, ошибки eslint? вкомитал функционал, который не был реализован к дедлайну?

: Думаю легкие исправления типа еслинта  - если студент делал это самостоятельно говорят прежде всего о том что он стремиться делать все аккуратно но пока не успевает, в любом случае это достойно уважения ибо лучше позже чем никогда, другое дело если студенту постоянно нужно об этом напоминать что может немного напрягать учебный процесс - тогда можно снять баллы но не очень много в пределах 5%

P.S. На своем наборе иногда замечал в тасках указания о том как будут вычитаться баллы, я человек не сильно мнительный, но все равно впечатление от таска немного развеивалось, вопрос формулировок очень важен в условиях гонки, я предлагаю идти от презумкции виновности к презумкции невиновности (допускать возможность форс-мажера) и от системы наказаний к системе поощрений (давать возможность зарабатывать недостающие баллы)

**Comment by irinainina** [comment]
Ментор сразу сказал, что нужно успевать делать таски до дедлайнов, чтобы он  успевал проверить/подсказать что исправить. Успеваю, это в моих интересах. То есть я делаю задание как могу и как его понимаю, он смотрит что получилось, говорит, что исправить/улучшить, я исправляю, он ставит оценку по конечному результату с учётом исправлений. Задания сдаются до дедлайна. Затягивать со сдачей до следующего дедлайна, как предлагают выше, нет смысла, потому что тогда нужно будет делать следующее задание, а не переделывать предыдущее. Преимущества такого подхода. Я: могу увидеть свои ошибки, исправить их, сделать задание лучше, чем если бы делала его без подсказок, учусь новому. Он: видит текущий уровень, основываясь на нём может подсказать что сделать, чтобы он стал чуть выше, видит, что его советы учитываются и идут на пользу, учит и понимает, что научил именно он. Но здесь важна взаимная ответственность. Я понимаю что ему нужно время, чтобы посмотреть и проверить таск, он - что мне тоже нужно время, чтобы исправить ошибки. Задание проверяется в течении двух-трёх дней. Если менторы неделями не находят времени, чтобы проверить таски, такой вариант, разумеется, не сработает.
Что касается отказа от оценок. Если люди волнуются из-за баллов, значит, баллы для них важны. Забирать у людей то, что для них важно. чтобы они не волновались, так себе идея. Вспомните разницу между экзаменом (оценивается баллами) и зачётом (сдал/не сдал) к чему больше готовились и какой предмет в итоге лучше знали. То есть переход на зачётную систему снизит уровень подготовки. Сознательно снижать качество знаний только для того, чтобы люди не переживали из-за оценок? Ну, не знаю. По-моему, это не совсем тот результат, к которому нужно стремиться.

**Comment by sonic-interlock** [comment]
имхо, сперва лучше разобраться зачем нужны оценки (и нужны ли вообще), а потом уже отталкиваться от этого

**Comment by davojta** [comment]
> имхо, сперва лучше разобраться зачем нужны оценки (и нужны ли вообще), а потом уже отталкиваться от этого

@sonic-interlock так вроде ж понятно зачем

- один из способов оценки и самоконтроля знаний 
- способ мотивации студентов
- способ отбирать студентов в этапы \ лабу Епама \ советовать в другие конторы
- понятный способ сбора фидбека о задании (менторы понимают что такое отметка, студенты понимают и организаторы понимают)

**Comment by sonic-interlock** [comment]
@davojta отнюдь, раз уж вопросы возникают :)

Если по теме, то мне кажется, что оценивать работы заново будет очень сильно напряжно и лучше будет оставить как есть. Все-таки, чтобы узнать сделана  фича или нет, ментор не нужен. А если не знаешь как делать, можно и до дедлайна с ним общаться

**Comment by dzmitry-varabei** [comment]
Из общения с @davojta по поводу критериев оценки, на примере `piskel-animation-player.md` 
```
dzianis.sheka [7:43 AM]
Почему нужна декомпозицая оценки по фиче на подпункты
1) умные и так все делают
2) средние, кто учаться - получается если не могут чтото сделать - даже пытаться не будут
3) слабые вообще не будут браться, тк слишком сложно в короткое время
4) если есть больше легких градаций - проще психологически делать
```
Полность согласен с позицией Дениса

**Comment by dzmitry-varabei** [comment]
По результатам обсуждения оформил https://github.com/rolling-scopes-school/docs/issues/51
