### ISSUE TITLE
Определить скоп, для которого студенты должны писать юнит тесты при выполнение заданий

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#19]
Варианты:
- тестируем только чистые функции. Например, минимум 3 чистые функции должно быть протестировано 
- тестируем то, что попросил тестировать ментор
- просто написать 10 любых тестов

**Comment by aleksei-bulgak** [comment]
Честно признаться у нас в рамках курса было мало про тестирование кода. Просто в рамках задания было указано что код должен быть покрыт тестами.
Но проблема в том, что многие не представляют как правильно писать тесты, какие кейсы нужно покрывать тестами, что нужно не только success кейсы писать, но и fail cases, что каждая функция в коде должна быть покрыта минимум тремя тестами(это уже мое личное мнение).

Если поставить правильно писать 10 тестов, то не факт, что у человека сложится правильное понимание и мнение о тестах. мб нужно еще показать какие-нибудь CI/CD тулзы, чтобы люди смогли понять когда написаные тесты могут помочь.

**Comment by Shastel** [comment]
Просто требовать ковередж 60% и возложить на ментора контроль логичности этого всего?

**Comment by aleksei-bulgak** [comment]
К сожалению на личном опыте знаю, что покрытие даже 80% не гарантирует того что все важные кейсы покрыты и что тесты нормальные

**Comment by Shastel** [comment]
> возложить на ментора

**Comment by davojta** [comment]
Мне кажется что тесты - это признак талантливости студента \ его отличительности

То есть это дополнительное требование, задача со звездочкой. В текущую программу 2 этапа тестирование юнитами не влазит. Может на 3 внести? И все задачи там уже должны будут покрываться тестами?

То есть
2 этап - просто тесты, какие работают - ментор подправляет, если есть желание, студент сам разбирается
3 этап - уже норм таску по тестам давать

**Comment by feugenix** [comment]
> Может на 3 внести? И все задачи там уже должны будут покрываться тестами?

Нужна будет лекция по тестам. И, скорее всего, мастер класс или воркшоп, с разбором типовых ситуаций: как лучше проверить апишку, как лучше замокать данные или дом, зачем нужны setUp/setDown и тд. Иначе студенты сильно запутаются, пытаясь понять это сами.
