### ISSUE TITLE
Cертификат RSSchool 2.0

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#20]
- Определить и прописать минимальные требования для получения сертификата
- Разделить сертификат на 2 части
   - первую часть человек получает после окончания обучения
   - вторую часть получает после окончания менторинга в одном из циклов RSSchool 
- Переработать дизайн
- Что необходимо указывать на сертификате?
   - пройденные таски, интервью? 
   - благодарности от других студентов? 
   - фио ментора? 
- ???

**Comment by Zerovers** [comment]
1. Сдать все таски с каким-то минимальным проходным балом(по кажому таску, по финальному или в сумме), 
2. ??
3. Дизайн вполне и счас
4.1 Какое направление окончил и что это успешно думаю достаточно
4.2 Таски всеравно проще держать на гитхабе или CV, всеравно придется их показывать при поиске работы

**Comment by aleksei-bulgak** [comment]
`пройденные таски, интервью?` - это лично мое мнение, но сертификат - это не резюме, а просто показатель оконченных курсов. Он сам по себе является подтверждением того, что студент сделал все, что входило в задачи курса.

`благодарности от других студентов?` -  в бытность работы в ипаме была прикольная штука как heroes portal. и там можно было оставлять благодарности коллегам в виде бейджиков. можно подумать что-то в этом плане и к примеру каждую благодарность отображать на сертификате в виде звездочки или еще чего-нибудь

**Comment by dimadk24** [comment]
1. Нужно решить, формировать минимальный порог на основании каждого таска или в целом по скору. Если в целом по скору, тогда можно сделать хуже один таск, зато лучше другой и все равно получить сертификат. Сейчас даже если ты все таски сделал отлично, кроме одного, ты не получишь сертификат.
2. То есть получается будет сертификат студента и сертификат ментора?
3. Предлагаю для ТОП 3 студентов добавить на сертификат медаль золотого, серебрянного и бронзового цветов. И цифрой написать место на сертификатах этих 3 студентов.
4. Согласен с тем, что не надо добавлять много инфы про таски, ментора и тд. Не влезет все, или будет смотреться слишком переполнено.

**Comment by uniorunr** [comment]
1. Имя ментора (либо имя и контакт)  -  хорошая идея. Это будет что-то типа референса. 

И если студент захочет показать этот сертификат при прохождении интервью на работу, то у нанимателя будет возможность связаться с ментором и уточнить у него по поводу этого студента. 

2. Думаю сертификат должен выдаваться по общему скору. Плюс дополнительные требования по важным таскам. 

Например: сертификат выдаётся тем, кто набрал скор минимум 60% от максимального. Плюс финальный таск выполнен на 70%+,  ютуб на 60%+ и есть презентация

**Comment by Shastel** [comment]
1. Имя ментора довольно бесполезно, так как мы не хотим ранжировать студентов по ментору.
2. Сертификат можно выдавать учитывая сколько процентов людей набрали баллы, топ 60% получают сертификат. 
3. Медали отличная идея, но я предлагаю увеличить количество: 1 золото, 2 серебра и 3 бронзы

**Comment by cathzetjo** [comment]
1. **Баллы** - очень субъективная вещь и личное видение каждого конкретного ментора. Поэтому выдача сертификата в зависимости от максимального скора по школе - это не совсем объективно и это переменная величина от набора к набору.
Сертификат логично может получить студент, завершивший все таски к примеру с минимум 50%  от скора по каждому из тасков. Тогда условия получения сертификата меняться не будут. Если у студента высокий общий скор, но какой-то таск был не выполнен вообще или выполнен с очень низким скором по каким-то объективным причинам, дать штрафное время его сделать "под страхом" выдачи сертификата. ).Эти условия думаю стоит прописать сразу на инф.страничке о курсе, чтобы не было потом пустых стенаний, а я не знал, а мне никто не сказал.)
2. Хорошая идея **сертификатов для менторов**. Можно сделать градацию типа обычный, бронзовый, серебряный, золотой, платиновый - в зависимости от количества курсов менторинга и получения хотя бы одним из студентов группы ментора сертификата об окончании. У кого %% прохождения студентов выше 50%, бейдж прям бриллиантовый даже можно навесить дополнительно)
**Сертификаты для студентов** тоже можно сделать например для топ 5 золотой, топ 20 серебряный, топ 50 бронзовый. Остальным обычный. Красить можно хедер например или SVG'шку RS Sсhool.
3. Сертификат ([нашла такой](https://imaguru.by/wp-content/uploads/2018/03/rsschool-certificate.png)) как раз по-моему и просится, чтобы его немного "перегрузили" )) .Понравилась  идея с медальками **за помощь** студентам, т.к. если писать текстовые благодарности - это загромоздит документ. Можно придумать пару типов медалей на софт и хард скилы и назначать проанализировав например gratitude.
**Пройденные таски** в ёмком формате мне кажется указать будет не лишним, чтобы было понятно, что пройдено именно на этом курсе.
Указывать **пройденные интревью** можно например с общей балльной оценкой менторов. Например пройденных интервью - 2 с процентом успеха 69% и 94%. Тоже можно бейджами сделать. Т.к.менторы заполняют форму по итогу интервью, то эту оценку более или менее можно объективизировать (нет такого слова, но не знаю как по-другому сказать)).
**ФИО ментора** кажется лишней информацией на сертификате. При необходимости его могут спросить у студента, как спрашивают рекомендателя с предыдущего места работы. Можно рекомендовать студентам в CV указывать (по предварительному согласованию с ментором), контактные данные ментора.

**Comment by auseika** [comment]
Хацелася б каб сертыфікат неяк адлюстроўваў тое, як чалавек працаваў на курсах. Балы - поўная абстракцыя, іх нельга пісаць туды, ясная справа. Пазіцыя ў скоры таксама можа быць даволі ўмоўнай, з маленькай абсалютнай розніцай (у балах) для студэнтаў, якія знаходзяцца праз 10-20 пазіцый.

Рашэннем можа быць сістэма ачывментаў - студэнтам можна выдаваць бэджы за тое, што яны юзаюць добрыя практыкі/здаюць да дэдлайна/дапамагаюць іншым, але гэта даволі шмат працы. 
Яшчэ адзін варыянт - розніца ў % скора студэнта і медыяннага скора ўсяго набору, рэалізаваць прасцей, толькі трэба прапрацаваць пытанне рэпрэзентатыўнасці такога значэння.

**Comment by cathzetjo** [comment]
> Хацелася б каб сертыфікат неяк адлюстроўваў тое, як чалавек працаваў на курсах. 
> ...
> Яшчэ адзін варыянт - розніца ў % скора студэнта і медыяннага скора ўсяго набору...

На мой взгляд это похоже в итоге на что-то типа - сертификат мы конечно выдали, но результаты у студента по сравнению с другими  средненькие, так что смотрите сами брать или не брать на работу))
Отражать в сертификате стоит как мне кажется позитивную информацию - бейджы весьма неплохое и нейтральное решение.

**Comment by davojta** [comment]
Свои 5 копеек

1) выдавать сертификат за
- минимальные таски - интервью у ментора, презентация, финальная таска и таски 3 этапа (коллективный хакатон + одна таска с фреймворком) 
- учитывать минимальное значение скора - гдето 60% от максимального. Тут можно каждый набор варьирвать от максимального бала на курсе

2) указывать ментора - хорошая идея. + еще отзыв ментора можно опционального отображать ) *все равно сертификат больше как памятный знак*

3) давать бейджики 
- мне хочется показать что студент был активистом! 
- Что он был в топе по задачам, 
- что он помогал проводить \ проверять задания. 

4) сертификат менторинга - тут я думаю важно
- менторство 2 набора и больше
- менторство 8 студентов и больше
Важно отобразить чтение лекций и участие в орг деятельности (присутствие на митапе - сдачи презентации, помощь в составлении заданий, проверки больших тасков (финальная таска, культурный портал, финальная таска 3 этапа)
- я пока боюсь считать по менторам и насколько выпускники успешны - тк многое зависит не от ментора. Но если человек отменторил 20 - 40 - 100 человек - это круто, но не знаю нужен ли ему сертификат 

Было бы круто двигаться к бейджам и ролям. Это поможет курсам и качеству обучения )

**Comment by webmakaka** [comment]
Привет! Из обсуждения в чате по node от закончивших курс.
Попросили написать здесь для обсуждения.

![pic1](https://user-images.githubusercontent.com/10372159/127855839-ffc8236e-1da1-4eed-a1aa-491576e25897.png)

![pic2](https://user-images.githubusercontent.com/10372159/127855853-aeb86e97-a383-45ed-a799-f7fb920bf2b8.png)

![Screenshot from 2021-08-02 14-37-48](https://user-images.githubusercontent.com/10372159/127856080-6f62fade-c269-4bed-90f8-d6c11aed11c4.png)

**Comment by davojta** [comment]
Мне нравится лига и ачивки ) Это должно хорошо смотреть в онлайн cv и можно гордиться потом)

**Comment by webmakaka** [comment]
Еще 1 идея от "генератора идей". На этот раз по кроссчеку.
Проверяющий не только проверяет 4 работы, но и выбирает ту, которая ему понравилась больше остальных. Мелочь, а приятно. 

А в score добавить еще 1 поле "зрительские симпатии"

По завершении курса, можно понять у кого оказались наиболее понравившиеся работы и поизучать их. Всегда же есть чему учиться у лучших. Остается только найти этих лучших.

Можно также наиболее понравившейся работе накинуть какое-то количество баллов, даже выше максимального. Скажем, если максимум 100, можно и накинуть 10.

**Comment by cathzetjo** [comment]
> Можно также наиболее понравившейся работе накинуть какое-то количество баллов, даже выше максимального. Скажем, если максимум 100, можно и накинуть 10.

Нравится/не нравится это же вкусовщина  часто. Мне кажется добавлять за это баллы не совсем корректно. Что это будет за пункт ТЗ- у проверяющего остались приятные впечатления +10?)
  
А вот выделять лучшие работы автоматически- хорошая идея. Думаю некоторые ленятся специально   куда-то какие-то ссылки отправлять.)

**Comment by webmakaka** [comment]
По работам с курса NODE и NODE + AWS могу только судить. 
В некоторых все пункты формально соблюдены, но блин, не нравится и все.  Прям чувствуется запашок. 
А есть прям отличные решения (некоторые я форкал себе), которые можно выделить на фоне других.

**Comment by cathzetjo** [comment]
> В некоторых все пункты формально соблюдены, но блин, не нравится и все. Прям чувствуется запашок.

А что значит формально? Пункт либо выполнен , либо нет. 
Мне кажется к студентам стоит быть добрее.
Всякие Фе они ещё успеют выслушать от заказчиков в реальной жизни.)

**Comment by webmakaka** [comment]
Ок. Вариант с просто выбором наиболее понравившейся работой мне видится интересным.
(Ну и чтобы это отображалось где-то, например в таблице score).

**Comment by AV-Shell** [comment]
По курсу js могу судить - очень часто попадались все 4 работы из которых ну ни как не хочется выбирать лучшую.  Я бы не вводил такое правило, выбирать лучшую из тех, которые попались на кроссчек. Вот напоминать, что если попались очень хорошие работы и вы хотите их отметить, то есть форма куда можно засабмитать ссылку на хорошую работу,  - стоит.  Просто если каждый будет выбирать лучшую работу из 4-х то действительно классные работы могут затеряться на их фоне. (А такие редко, но попадались )
