### ISSUE TITLE
Автоматизированное тестирование тасков

### ISSUE THREAD

**Issue by medinsky** [rolling-scopes-school/docs#22]
Всем привет!
Выношу на обсуждение и предложение сделать автоматическую проверку тасков.

Это будет удобно менторам и студентам.
Ментор, проверяя ваш таск может запустить тесты, если тесты не проходят - то всё, досвидания и даже проверять не надо и ему сразу по результатам наших тестов будет понятно что студент сделал.
Студент, пытаясь удовлетворить тестам, во первых, будет писать возможно более качественное приложение, во вторых научится работать и узнает что такое Test Driven Development (TDD), и также у него будет наглядная картина результата куда нужно стремится. 

И это не отменяет того момента что и студентам нужно будет писать свои тесты. Тестирование это хорошо. Т.к. когда студент поймёт что его код невозможно протестировать никак кроме снапшотов, тогда он научится писать функции меньше, чище и лучше. 

Итак, посмотрев на сайте FreeCodeCamp как у них сделаны таски и проверка, почему мы хуже?)

К примеру у них есть такое задание: https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-survey-form , где описаны UserStory и внизу дана ссылка на тест-раннер https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js который проверяет выполнение таска в автоматическом режиме. 
Я набросал этот таск в codepen: https://codepen.io/medinsky/pen/PvGMqK
Посмотрите как удобно иметь такую тест-систему, как она работает. 

![image](https://user-images.githubusercontent.com/48988087/58235941-88578600-7d4a-11e9-9f14-d6dcb95ac08a.png)

где мы можем выбрать таск , который проверяем

![image](https://user-images.githubusercontent.com/48988087/58236000-a329fa80-7d4a-11e9-80b8-da732148d14b.png)

и чтоб не мешалась, её можно свернуть
![image](https://user-images.githubusercontent.com/48988087/58236019-ade48f80-7d4a-11e9-92a9-50838f6cf8de.png)

в случае, если какой-то тест завалился, то мы получаем хороший фидбэк от тест-системы
![image](https://user-images.githubusercontent.com/48988087/58236508-b7bac280-7d4b-11e9-83a9-078c31db6d74.png)

в общем, как будет у меня времени побольше, я постараюсь набросать нечто подобное для авто-тестов таска CV к примеру. Конечно если есть добровольцы которые могут снять эту задачу с меня, это тоже хорошо т.к. время иногда сложно выкроить

**Comment by aleksei-bulgak** [comment]
я понимаю что уже всех задолбал с идеей CI/CD и Travis :)
но почему бы не предложить студентам делать билды на трэвисе?
Как я понимаю результат таска всегда представляет собой pull request. и там сразу будет видно что все ок или нет

![image](https://user-images.githubusercontent.com/1677410/58239061-09b21700-7d51-11e9-9658-1d5b5096e2d8.png)
 
Travis это как пример. на деле есть много разных тулов с поддержкой Github

Просто с тулами аля Travis, CircleCI можно получить реальный опыт использования тулов, которые с какой-нибудь минимальной вероятностью используются у кого-нибудь на проекте

**Comment by mikhama** [comment]
Ну тут еще дело в том что не все успевают написать тесты))

**Comment by medinsky** [comment]
@mikhama не все успевают написать ещё основной код приложения)))

**Comment by medinsky** [comment]
@aleksei-bulgak если помнишь, то вспомни какой был страх и паника у студентов этого набора когда они лекцию по MVC получили :) думаешь CI тулы им будет освоить просто?)

**Comment by aleksei-bulgak** [comment]
@medinsky согласен. но на начальном этапе можно это упросить показав примерный шаблон теплейта и сделать презенташку на минут 20. но тут уже решать организаторам

**Comment by lion9** [comment]
Использовать Selenium или Puppeteer было бы крайне неплохо. Хотя бы для задач, которые повторяются. Типа CV или YouTube

**Comment by daniil-loban** [comment]
Тема сама по себе очень интересная (как и сложная) ведь даже не все что работает и проходит тесты написано качественно и CI думаю в этом случае не очень помогут.
