### ISSUE TITLE
корректировка вопроса RSS Test. (некритичное)

### ISSUE THREAD

**Issue by AlexKhvostov** [rolling-scopes-school/docs#227]
![image](https://user-images.githubusercontent.com/42321432/159183737-df466ad2-0c1d-4def-abf9-07c812c24be2.png)
Некорректная формулировка вопроса RSS Test.
Под такую формулировку подходят несколько вариантов.

**Comment by FrontKid** [comment]
Во 2-м и 3-м вопоросах нужно просматривать каждую страницу а их там 58+ поэтому логично и практично и удобней всего искать через поиск по нику

**Comment by stardustmeg** [comment]
The question was replaced. Not relevant anymore
