### ISSUE TITLE
Правила хорошего тона студентов RSSchool 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#23]
Фидбек от ментора
```
У меня просьба, обозначить студентам, что номер телефона и соответсвенно 
мессенджеры, типа телеги - это крайний способ связи,  достаточно заассайнить реквест, немного пригорело, что мне пишут в час ночи с вопросом, а буду ли я сразу проверять или нет
```
- ставить Star проектам, которыми пользуетесь
- говорим спасибо в канале #gratitude или в RSSchool APP, если вам помогли 
- ....

Информация будет добавлена в https://github.com/rolling-scopes-school/docs/blob/master/students.md

**Comment by greatorangejuice** [comment]
Пусть тогда ментор указывает приоритетный способ связи. Думаю, что большинство всё равно общаются со студентами через мессенджеры. Плюс каждый студент хочет быть уверен в том, что PR действительно пришел и его точно проверят.

А конкретно из предложений, я бы прописал вот что:  важен шаринг знаний, то есть если студенту помогли с каким-то вопросом и он видит, что у других студентов подобные сложности возникли, то очень желательно, чтобы данный студент не проходил мимо и так же помог. 
Ну и шарить полезные ссылки тоже полезно и важно) Что у нас и делают

**Comment by medinsky** [comment]
менторы также должны указывать предпочитаемый способ связи а также часы, когда можно ему писать, например тел. +123456789 с 9.00 до 21.00 МСК, так будет правильней

**Comment by dzmitry-varabei** [comment]
@greatorangejuice @medinsky спасибо за советы! закинул в доки и форму для менторов
