### ISSUE TITLE
Неправильная ссылка на discord курса «NodeJS in AWS»

### ISSUE THREAD

**Issue by natein** [rolling-scopes-school/docs#243]
На странице https://docs.rs.school/#/rs-school-chats указана неправильная ссылка на дискорд курса «NodeJS in AWS».
Сейчас ссылка ведёт на курс «NodeJS». Нужно заменить на https://discord.com/invite/ATsHAqCsnw

**Comment by auchynnikau** [comment]
@natein PR #251 fixing this issue was published, please, take a look
