### ISSUE TITLE
Опечатка в тексте в разделе Cross-check

### ISSUE THREAD

**Issue by DmitriyAndriyanov** [rolling-scopes-school/docs#264]
https://docs.rs.school/#/cross-check-flow

Раздел "[Шаг #1 Отправка работы на проверку](https://docs.rs.school/#/cross-check-flow?id=%d0%a8%d0%b0%d0%b3-1-%d0%9e%d1%82%d0%bf%d1%80%d0%b0%d0%b2%d0%ba%d0%b0-%d1%80%d0%b0%d0%b1%d0%be%d1%82%d1%8b-%d0%bd%d0%b0-%d0%bf%d1%80%d0%be%d0%b2%d0%b5%d1%80%d0%ba%d1%83)"

Текущий текст "Ссылку можно сабмитать несколько раз - сохраняется последняя."

Необходимо исправить слово "сабмитать" на "сабмитить".

**Comment by matthewTheWizzard** [comment]
Сделано. Ждем подтверждения, спасибо за репорт!
