### ISSUE TITLE
Новый набор студентов стартует каждые полгода? 

### ISSUE THREAD

**Issue by AnNataly** [rolling-scopes-school/docs#294]
Здравствуйте. 
Вот здесь https://github.com/rolling-scopes-school/tasks?tab=readme-ov-file присутствует фраза "Новый набор студентов стартует каждые полгода". 
При этом в видео говорят, что набор раз в год.

**Comment by lyutails** [comment]
ty :)
created PR https://github.com/rolling-scopes-school/tasks/pull/1719
