### ISSUE TITLE
Как улучшить документацию http://docs.rs.school

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#33]
Буду рад любым комментариям, замечаниям, исправлениям

**Comment by lion9** [comment]
Регистрация в этих системах **упращает** работу HR специалистов компании EPAM. - упрощает, HR**-**специалистов

**Comment by lion9** [comment]
С вашей стороны необходимо *тольк* время и желание - только

**Comment by lion9** [comment]
Пойти на курсы английского языка до **получение** уровня - получения

**Comment by lion9** [comment]
**Discord: русский, английский**
мяркую, людзі гэтага не ўхваляць

**Comment by dzmitry-varabei** [comment]
@lion9 спасибо огромное! все исправил!

**Comment by cathzetjo** [comment]
Документация отличная. Подборка просто супер.
1) Без поиска сложно ориентироваться.
2) https://docs.rs.school/#/rs-school-overview?id=СЕРТИФИКАТ
заменить текст, например на :  Сертификат об успешном прохождении курсов выдается студентам, прошедшим три этапа обучения и набравшим установленное количество баллов по ключевым заданиям. Перечень заданий и планка по баллам устанавливается для каждого потока отдельно. Пример требований к сертификату выпуска 2019Q1 : https://docs.rs.school/#/rs-school-certificate.
3) https://docs.rs.school/#/README?id=telegram
Нерабочая ссылка https://t.me/therollingscope
4) https://docs.rs.school/#/rs-school-overview?id=Принципы-школы
Культура менторинга - > можно здесь добавить ссылку на https://docs.rs.school/#/rs-school-mentor

**Comment by dzmitry-varabei** [comment]
@cathzetjo спасибо за замечания и предложения! всё исправил, поиск включил!

**Comment by Sijioth** [comment]
Есть вопрос по чатам в Discord. В первую очередь по следующим:
![Screen Shot 2019-09-26 at 1 09 34 AM](https://user-images.githubusercontent.com/47459465/65647039-eb616e00-e005-11e9-823c-fbb7bbfceafc.png)
\#main отсутствует в принципе, а \#programming-tasks-help уже в архиве (да и ссылка на Padawans уже, я так понимаю, не актуальна).

Далее, \#git предлагаю переместить в категорию RS2019Q3 и переименовать в git-RS2019Q3 (как оно есть в Discord) а саму категорию Questions упразднить, т.к. в том же Discord она отсутствует в принципе.
И чтоб было совсем по фен-шую: добавить в ту же категорию (RS2019Q3) каналы \#markup-tasks и \#algorithmic-tasks с пояснением.
Ну и если все же положительно решится судьба второго канала \#materials, то и его также стоит добавить.

**Comment by dzmitry-varabei** [comment]
@Sijioth обновил. 
Кроме второго канала materials

**Comment by VladimirStavinchuk** [comment]
1. В разделе **Нотификации** https://docs.rs.school/#/notifications слово "апрувнуты". (Вы, как ментор, **апрувнуты** на курс (содержит ссылки для подтверждения участия как ментор, не требует подписки).
2. В разделе **Распределение по командам** https://docs.rs.school/#/teams картинки не подгружаются.

**Comment by turn2river** [comment]
Привет! 
В разделе про наименование коммитов (https://github.com/rolling-scopes-school/docs/blob/master/docs/git-convention.md#%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE-%D0%BB%D0%B8-%D1%80%D0%B5%D0%B2%D0%B5%D1%80%D1%82%D0%BD%D1%83%D1%82%D1%8C-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B7%D0%B0%D0%BF%D1%83%D1%88%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B2-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82-%D0%B1%D0%B5%D0%B7-%D1%81%D0%BD%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8), в FAQ не совсем верная формулировка:

`Можно ли ревертнуть отправленный (запушенный) в репозиторий коммит без снижения оценки?` 

предлагаю её заменить/добавить на:

`Можно ли изменить комментарий к отправленному (запушенному) коммиту без снижения оценки?`

Ибо понятие 'ревертнуть' не сработает в случае с автопроверяемыми тасками, таким как CV

**Comment by AntonVarlamov** [comment]
что за слово сабмитуть? если должно быть сабмитнуть, тогда поправьте
![image](https://user-images.githubusercontent.com/37105065/158106982-b1c31864-4fd3-449c-8d1b-3e84f5bf8148.png)

**Comment by AntonVarlamov** [comment]
еще  такая проблема, что при переходе на другие вкладки в доке скроллинг остается на том же уровне, хотя по идее должен переходить к началу страницы

**Comment by dzmitry-varabei** [comment]
> сабмитнуть

привет! спасибо! поправил!

**Comment by nik2218** [comment]
Шпаргалка по markdown разметке не актуальная 
![image](https://user-images.githubusercontent.com/79281924/171555858-ce2702ae-012d-434c-b38d-22e5c634296b.png)

По ссылке от гита есть актуальное руководство
https://gist.github.com/Jekins/2bf2d0638163f1294637

**Comment by ghost** [comment]
Здравствуйте, нашёл небольшую опечатку в Менторинг>>Как стать ментором>>Джентельменское соглашение>> **Ментор имеют первоочередное право на** может изменить на Ментора имеют или Ментор имеет. Спасибо

**Comment by Arterixs** [comment]
Здравствуйте! 
В связи с недавним бурным обсуждением темы "Оскорбления в личных сообщениях", предлагаю внести в документацию в раздел "Нормы поведения" пункт следующего содержания, чтобы попытаться предотвратить возникновение подобных ситуаций и споров по данной теме:
_

> "Так же мы хотим обратить внимание на соблюдение дружелюбной атмосферы в рамках межличностного общения между студентами школы на любых каналах связи (личные сообщения дискорда, телеграма, мэйла и т.д.) касаемо учебного процесса: проведение кроссчека, обсуждения заданий и т.п. Будьте вежливыми, тактичными и внимательными друг к другу.
> В случае нарушения данной рекомендации и получении по этому поводу жалобы, администрация школы сохраняет за собой право оценки тяжести нарушения на своё усмотрение и вынесение соответствующего наказания, вплоть до исключения из школы.
> Пожалуйста, соблюдайте правила хорошего тона.”

_
В случае принятия данной корректировки, так же предлагаю внести в RSS Test несколько вопросов напрямую отсылающих к данному пункту правил, чтобы акцентировать на нём внимание учащихся.
