### ISSUE TITLE
Создать\Интегрировать курс английского с программой RS school

### ISSUE THREAD

**Issue by Sannnao** [rolling-scopes-school/docs#38]
Идея состоит в том, что бы организовать на курсе RS School параллельное изучение\практику английского языка. Пока из идей следующее:
1. Сотрудничать со школой иностранных языков по принципу аудитория <> выгодные предложения.
2. Объединиться с некоммерческими организациями, которые проводят собрания типа English club
3. Организовать собственный курс: каждый набор в RSS встречаются люди с хорошим знанием английского. Они могли бы стать двигателем прогресса в смысле pay it forward - они могут вернуться не только в роли ментора, но и в роли english активиста. Помочь разработать программу \ собрания \ интерактив.

**Comment by ange2912** [comment]
Я думаю пункты 2 и 3, особенно 3 - можно сразу и внедрять. Главное собрать подходящих людей вместе. Если летом это можно было сделать, например, в парке, то с наступлением холодов - надо искать еще и место.

**Comment by dzmitry-varabei** [comment]
@Sannnao опиши плиз концепт текуших RS English club. Добавим в документацию школы в раздел [Типы занятий](https://docs.rs.school/#/stage1?id=%d0%a2%d0%b8%d0%bf%d1%8b-%d0%b7%d0%b0%d0%bd%d1%8f%d1%82%d0%b8%d0%b9)

**Comment by Sannnao** [comment]
> @Sannnao опиши плиз концепт текуших RS English club. Добавим в документацию школы в раздел [Типы занятий](https://docs.rs.school/#/stage1?id=%d0%a2%d0%b8%d0%bf%d1%8b-%d0%b7%d0%b0%d0%bd%d1%8f%d1%82%d0%b8%d0%b9)

На данный момент встречи проходили в формате создания предложений с выбранным словом каждым участником и потом по очереди каждый участник озвучивал предложение. При необходимости обсуждались ошибки. Этот контент был придуман для пилотного запуска первых встреч и в дальнейшем возможно придумается больше разнообразного и интересного контента!

**Comment by dzmitry-varabei** [comment]
@Sannnao хорошо, спасибо!
