### ISSUE TITLE
Отдельный курс по React Native 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#46]
- TBD

**Comment by auseika** [comment]
1. Expo нават не разглядаць, гэта тупік, з яго давядзецца валіць рана ці позна, і лепей увогуле не пачынаць ў такім выпадку.
2. Зрабіць фокус на асаблівасці кросплатформенасці. Не ўсе рэчы працуюць аднолькава на iOS/Android. Тут праблема можа быць з тым, што не ва ўсіх ёсць мак/іпхон каб гуляцца. `KeyboardAvoidingView`, цені етц.
3. Абавязкова патлумачыць, што адбываецца пад капотам, што такое Metro Bundler. Гэта важныя рэчы, яны дазваляюць хутчэй вырашаць ішуі якія не адразу атрымліваецца зразумець (сутнасць RN у гэтым, адзін вялікі хак жа). 
4. Asap даваць патыкацца ў жалеза, накшталт запэйрыцца з блютус-дэвайсам і падобнае. Гэта тое, чаго мне асабіста не хапала на вэбе (узгадваў у чаціку, як кепска працуе той жа WebBluetooth, і нават спікер на канфе прызнаў што ішуі ёсць, а сам уласна кажучы праз гэтае пытанне і паспрабаваў RN), можа _вельмі_ моцна заматываваць, іншы ўзровень ўзаемадзеяння кода і рэчаіснасці.
5. Асабіста мне хацелася б па AR пачуць чаго, тым больш, што Viro зрабіўся опенсорсным. Не на кожным дэвайсе завядзецца ARCore/ARKit, але там здаецца на эмулятары штосці зрабіць можна, трэба зарысёрчыць.

Яшчэ, акрамя ўсяго гэтага, бачу праблему ў тым, што не кожная машына пацягне андроід эмулятар так, каб з ім можна было нармальна працаваць, і, ў сваю чаргу, на дэвайсах не заўсёды можна ўсё затэсціць, бо ў некага, напрыклад, няма выразу ў экране/стары андроід етц. У мяне машына з i5-5200U і 12 гб памяці прасаджвала фпс у вскодзе да 3-5 калі эмулятар з парай кантэйнераў докера круціўся. І гэта пад лінуксам, на віндзе ўсё горш.

Магчыма даў бы якую таску з MobX, калі час будзе, вельмі шмат дзе юзаецца.

**Comment by dzmitry-varabei** [comment]
UPDATE:
- Приблизительная дата старта 1 февраля
- Продолжительность курса - 3 месяца
- 2 лекции в неделю 
- Формат - онлайн, через GoToWebinar
- По ходу обучения студенты будут делать социальный проект
- По окончанию обучения в EPAM Минск возможно трудоустройство для  5-7 студентов
- Требования к студентам: законченный RSSchool stage#2 + react basics

**Comment by pliashkou** [comment]
Вось прыкладны спіс заняткаў на 6-тыднёвы курс, кожны занятак па 1.5-2 гадзіны.
1. Installation, Components, TypeScript, Expo, Metro Bundler
2. Navigation, navigation stack, styling
3. Redux, Structure, state management, debugging
4. Forms, Validation
5. Rest APi, Firebase
6. WebSockets, GraphQL
7. Animations
8. React Native Community plugins overview
9. Building, signing, releasing to App Store & Google Play, working with Xcode and Android Studio
10. Usability practices, Performance optimizations techniques
11. Native Modules, bridge, linking
12. Headless JS, Hermes, App Center, Testing, CI/CD
