### ISSUE TITLE
Алгоритм взаимодействия ментор-студент во время проверки задания

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#51]
## Алгоритм взаимодействия ментор-студент во время проверки задания:

1. Студент выполняет задание в приватном репозитории
2. Студент создает и оформляет Pull Request. 
    - Правила оформления PR указаны [ниже](https://docs.rs.school/#/stage2?id=%d0%9e%d0%bf%d0%b8%d1%81%d0%b0%d0%bd%d0%b8%d0%b5-pull-request-%d0%b4%d0%be%d0%bb%d0%b6%d0%bd%d0%be-%d1%81%d0%be%d0%b4%d0%b5%d1%80%d0%b6%d0%b0%d1%82%d1%8c-%d1%81%d0%bb%d0%b5%d0%b4%d1%83%d1%8e%d1%89%d1%83%d1%8e-%d0%b8%d0%bd%d1%84%d0%be%d1%80%d0%bc%d0%b0%d1%86%d0%b8%d1%8e). 
    - Штрафы за нарушения дедлайна указаны [ниже](https://docs.rs.school/#/stage2?id=%d0%94%d0%b5%d0%b4%d0%bb%d0%b0%d0%b9%d0%bd%d1%8b). При применении штрафных коэффициентов, округление происходит в пользу студента. 
3. До выставления финальной оценки ментором, студент может продолжать реализовывать фичи после дедлайна со штрафом 50% к их стоимости в баллах. 
    - Названия коммитов должны явно говорить о реализованной фиче.
    - Студент должен оставить отдельный комментарий в открытом Pull Request о функционале, который был реализован и его стоимости в баллах с учетом 50% штрафа. 
    - При применении штрафных коэффициентов, округление происходит в пользу студента. 
4. Ментор проверяет PR, оставляет свои замечания и рекомендации по качеству кода (copy-paste, magic numbers, project structure, etc.) и реализованной функциональности.  Указывает предварительную оценку в комментарии. 
    - Оценка выставляется ментором на основании критериев оценки указанных для каждого задания. 
    - При выставлении оценки учитывается весь реализованный функционал. Например, студент выполнил минимальные требования не на 100 процентов, но выполнил часть дополнительных - все требования должны учитываться.
    - Ментор может выставить предварительную оценку авансом, с учетом того, что студент исправит все замечания ментора.
5. Студент в течении 3х дней исправляет замечания ментора. 
6. По результатам исправления ментор выставляет окончательную оценку в Score RS APP.
   - Ментор сам решает снимать баллы или нет за правки после дедлайна.

**Comment by irinainina** [comment]
Немножко дополнительных пунктов, может что-то покажется в тему )
1. В описание PR можно добавить демо приложения, которое студент размещает у себя на гитхабе в приватном репозитории, а затем деплоит на netlify. 
2. Уточнить должен ли студент уведомлять ментора о том, что выполнил таск. Если да, то в какой форме и в какие сроки. Если нет, об этом тоже желательно сказать.
3. Доработка таска после дедлайна исключительно с ведома и согласия ментора.
4. Штрафные баллы определяет ментор и может отказаться от них, если считает нужным.
5. Оценки авансом не нужны. В большинстве случаев студенты ведь не знают заранее что они смогут исправить и реализовать, а что нет.
6. То есть ментор оставляет замечания и даёт три дня на исправление. После этого ставит балл с учётом правок. Снимать баллы или нет за правки после дедлайна решает он же. Можно и не снимать.
