### ISSUE TITLE
Тут собираем идеи как можно улучшить сross-check процесс 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#55]

**Comment by Musmen** [comment]
Предложение - предоставить проверяющим текст PR студента, можно без коммитов - просто текст. Будет видна его самооценка. Возможно описан дополнительный функционал и другие нюансы, которые не заметны с первого взгляда. Всем должно быть проще.

**Comment by irinainina** [comment]
- После окончания кросс-чека таска Portfolio создать issue для апелляций по кросс-чеку и выложить ссылку на него в анонсах. В этом issue студенты, у которых результаты самооценки и кросс-чека отличаются на 10-20% и больше, могут попросить пересмотреть баллы за их работу. Для этого они выкладывают ссылку на страницу со своим проектом, ссылку на публичный репозиторий с проектом (чтобы можно было убедиться, что после сдачи работы она не менялась), и указывают баллы, которые получены, и которых работа, по их мнению заслуживает.  
- Возможно, результаты кросс чека можно обработать автоматически. Например, выявить проверяющих, которые выставили баллы, сильно отличающиеся от итоговых баллов за проекты, которые они проверяли, выявить проекты, у которых большой разброс по выставленным за них баллам.
- Увеличить количество проектов, которые проверяются при кросс-чеке, до пяти. Это сделает более заметными случаи,  когда кто-то значительно завышает или занижает баллы при проверке. Нагрузка на проверяющих при этом немного возрастёт, зато объективность проверки увеличится, и можно будет автоматически отбрасывать при выставлении итоговой оценки баллы, которые сильно отличаются от среднего. 
- Сделать обязательной самопроверку своей собственной работы по тем же критериям, по которым проверяются работы других студентов. Баллы за самопроверку учитывать при выставлении итоговой оценки. Также для каждого студента высчитывает коэффициент объективности - отношение выставленных им баллов к итоговым баллам за работы, которые он проверял.
- Было бы очень хорошо для объективности проверки выставлять не суммарный балл за проект, а заполнять форму, в которой указывать баллы за все элементы работы, которая проверяется.

**Comment by AnzhelaMartsinovich** [comment]
Можно оставить последнее слово за ментором, т.е. после проверки работы студентами, вы с ментором проходитесь по этим пунктам. Если не согласны с пунктом, то объясняете почему, если со всем согласны - то просто супер! И после такого подведения итогов, оценка выставляется ментором.

Кроме того, при выставлении оценки и описании пунктов что в работе ни так, хотелось бы возможности прикреплять скриншот страницы, для того что бы все замечания были обоснованы. Так же это нужно для того, если студент исправит что-то в проекте в период проверки работы, ведь истории коммитов мы не видим, а залить измененный проект на хостинг очень легко.
