### ISSUE TITLE
[Cross-Check Portfolio] - dermeister

### ISSUE THREAD

**Issue by dermeister** [rolling-scopes-school/docs#56]
1. Deploy - https://jovial-jepsen-269ba4.netlify.com/
2. Repo - https://github.com/dermeister/portfolio
3. 100 баллов - все сделано согласно заданию
4. Балл за cross-check из Score - 88

**Comment by amoebiusss** [comment]
Hi, here's my evalution.

### **Desktop** 
- **+** Avatar should be image in assets folder.
- **+** All links provided should navigate to real profiles on Social Networks.
- **±** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown. — **The panel expands only by clicking the text itself, not on any place of the panel**
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** Interactive arrows left and right, which switch the next and the previous project.
- **+** Carousel should be infinite.
- **+** Description should have the list of main projects features. At least 2 of them.
- **+** Interactive image in description (or whole description). When clicked, you should be navigated to project page.

###  **Mobile**
- **+** Avatar should be image in assets folder.
- **+** All links or icons should navigate to real profiles on Social Networks.
- **±** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown. — **The same as for desktop, the panel expands only by clicking the text itself, not on any place of the panel**
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** No arrows, project image should have all available width.
- **+** Swiper should be infinite.
- **+** Description should have the list of main projects features. At least 2 of them.
- **-** When the description button is clicked, it should show the description overlay above the image. And name near the button should switch text to 'hide description'. — **Description is being shown below the project image, not in an overlay. Button text does not change and remains the same - "Show description"**
- **+** Interactive image in description (except button and its label). When clicked, you should be navigated to project page.

###  **Project page**
- **+** 2 buttons exist on desktop version.
- **+** When you are on desktop, and click 'mobile', the view should be switched to centered mobile one and margins on left and right. Name of button should be changed properly. Second click will revert project to desktop view again.
- **+** When you are on desktop, and click 'back', you should be navigated to original portfolio page.
- **+** Only 1 button exists on mobile version.
- **+** When you are on mobile, and click 'back', you should be navigated to original portfolio page.

## Evaluation
100 points (max) - 5 (expansion panel issue on desktop/mobile) - 3 (button text issue) - 3 (description is not in an overlay on mobile phones) = **89 points**

#### And finally, some remarks. 

1. The page switches to desktop resolution only on 1300px, but according to stats, desktop resolutions start at lower values: https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide. This may be a reason why some of the students who checked the portfolio simply didn't see the slider arrows or 2 buttons on the desktop version and considered it an error.

2. ```<img class="rounded" src="assets/img/avatar.jpg" width="200px" alt="Avatar">``` this part of your code will cause a validation error. The value of the **width** attribute must be an integer **without a unit**, like ```<img width="200">```.

3. You've put the list of contacts (Skype, email, Github) into an organized list (```<ol>```) of breadcrumbs. But breadcrumbs are not just used for random lists, it's purpose is to indicate user location in a website. So, this is a kind of semantic problem. Additionally, is there a reason to make a list of contacts organized, or maybe ```<ul>``` would be more suitable?

And as you've used Bootstrap framework, please check its docs related to the use of breadcrumbs: https://getbootstrap.com/docs/4.0/components/breadcrumb/.

**Comment by amoebiusss** [comment]
Hi, here's my evaluation.

### **Desktop** 
- **+** Avatar should be image in assets folder.
- **+** All links provided should navigate to real profiles on Social Networks.
- **±** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown. — **The panel expands only by clicking the text itself, not on any place of the panel**
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** Interactive arrows left and right, which switch the next and the previous project.
- **+** Carousel should be infinite.
- **+** Description should have the list of main projects features. At least 2 of them.
- **+** Interactive image in description (or whole description). When clicked, you should be navigated to project page.

###  **Mobile**
- **+** Avatar should be image in assets folder.
- **+** All links or icons should navigate to real profiles on Social Networks.
- **±** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown. — **The same as for desktop, the panel expands only by clicking the text itself, not on any place of the panel**
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** No arrows, project image should have all available width.
- **+** Swiper should be infinite.
- **+** Description should have the list of main projects features. At least 2 of them.
- **-** When the description button is clicked, it should show the description overlay above the image. And name near the button should switch text to 'hide description'. — **Description is being shown below the project image, not in an overlay. Button text does not change and remains the same - "Show description"**
- **+** Interactive image in description (except button and its label). When clicked, you should be navigated to project page.

###  **Project page**
- **+** 2 buttons exist on desktop version.
- **+** When you are on desktop, and click 'mobile', the view should be switched to centered mobile one and margins on left and right. Name of button should be changed properly. Second click will revert project to desktop view again.
- **+** When you are on desktop, and click 'back', you should be navigated to original portfolio page.
- **+** Only 1 button exists on mobile version.
- **+** When you are on mobile, and click 'back', you should be navigated to original portfolio page.

## Evaluation
100 points (max) - 5 (expansion panel issue on desktop/mobile) - 3 (button text issue) - 3 (description is not in an overlay on mobile phones) = **89 points**

#### And finally, some remarks. 

1. The page switches to desktop resolution only on 1300px, but according to the stats, desktop resolutions start at lower values: https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide. This may be a reason why some of the students who checked the portfolio simply didn't see the slider arrows or 2 buttons on the desktop version and considered it an error.

2. ```<img class="rounded" src="assets/img/avatar.jpg" width="200px" alt="Avatar">``` this part of your code will cause a validation error. The value of the **width** attribute must be an integer **without a unit**, like ```<img width="200">```.

3. You've put the list of contacts (Skype, email, Github) into an organized list (```<ol>```) of breadcrumbs. But breadcrumbs are not just used for random lists, its purpose is to indicate user location in a website. So, this is a kind of semantic problem. Additionally, is there a reason to make a list of contacts organized, or maybe ```<ul>``` would be more suitable?

And as you've used Bootstrap framework, please check its docs related to the use of breadcrumbs: https://getbootstrap.com/docs/4.0/components/breadcrumb/

**Comment by moiseenokv** [comment]
Оценка по кросс-чеку "Portfolio" не была выставлена, хотя все 3 студента дали свое ревью.
Deploy - https://moiseenokv.github.io/portfolio/
Repo - https://github.com/moiseenokv/portfolio/
65-70 баллов: есть недочеты по респонсиву

**Comment by amoebiusss** [comment]
@moiseenokv привет! оформи, пожалуйста, отдельным issue

**Comment by amoebiusss** [comment]
@dermeister hi! i think closing the issue will stop reviewing process, are you sure?
