### ISSUE TITLE
[Cross-Check Portfolio] - Artur1986ad

### ISSUE THREAD

**Issue by Artur1986ad** [rolling-scopes-school/docs#60]
1. https://artur1986ad.github.io/My-portfolio/
2. https://github.com/Artur1986ad/My-portfolio
3. Данный task проверили 3 студента. И я в том числе тоже проверил у 3 студентов работу, и при этом в score 0 баллов . Но по отзывам студентов там не может быть 0 . Скорее всего произошел сбой, либо объясните почему в score 0 баллов
4. 0 баллов.

**Comment by apalchys** [comment]
@Artur1986ad У тебя 0 баллов, потому что у тебя проверена только одна работа из-за бага который был в системе.
Посмотри пожалуйста  мои анонсы от 12 Декабря в Discord #announcements, как пересабмитать ревью. Если будут вопросы, пиши мне в личные в Discord (apalchys)
