### ISSUE TITLE
[Cross-Check Fancy-Weather] - SkynerSany

### ISSUE THREAD

**Issue by SkynerSany** [rolling-scopes-school/docs#65]
1. https://skynersany.github.io/weather/
2. Верстка прототипа приложения не адаптивная и не резиновая - 20
В блоке 4 не отображаются широта и долгота - 10
При изменении города не меняется дата и время - 20
Не реализована возможность голосового поиска - 20
Смена языка реализована на 50% - 10
3. 0

**Comment by Ambrance** [comment]
Ваш максимум: 210 - 80 = 130
Еще ошибки: 
Какие-то астрономические величины температур при поиске - 5 баллов
![fancy-weather](https://user-images.githubusercontent.com/25725313/72218736-48e6df80-354f-11ea-843a-51d90ee82edb.png)
При генерации изображения учитывается только город и это только при загрузке приложения (при поиске просто рандомное изображение) - 5 баллов
Ошибки в консоли при отправке в поиск пустой строки - 5 баллов
Значения языка и единицы измерения температуры не сохраняются в storage - 5 баллов
Итог: 130 - 20 = 110 баллов
Очень красивая анимация с облаками. Жаль, что при cross-check не учитывается дополнительный функционал. Тогда оценка была бы выше..
