### ISSUE TITLE
[Cross-Check Fancy-Weather] - 'Victoria-Butrym'

### ISSUE THREAD

**Issue by Victoria-Butrym** [rolling-scopes-school/docs#66]
**1.** https://confident-goodall-1aae22.netlify.com/
**2.** 
 - Реализован поиск. Если в поиске вводится корректный запрос, все данные на странице, в том числе дата и время, обновляются в соответствии с указанным в поиске населённым пунктом: -30 (дата и время не обновляются)
- фоновые изображения генерируются с учетом поры года, времени суток, текущей погоды:  -10 (генерируется только с учетом местности)
- Реализована возможность переключения единиц измерения температуры: -5 (после поиска не меняется)
- Реализована возможность голосового поиска по названию населённого пункта: – 20
- Реализован перевод текста страницы (en/ru/be): – 20
- ошибки в консоли на любом этапе работы приложения: – 10

**3.** 97

**Comment by Ambrance** [comment]
Ваш максимум: 210 - 95 = 115
Еще ошибки:
При загрузке приложения в карте Брест, в заголовке Минск; название месяца не в коротком формате - 5 баллов
![Fancy Weather - API](https://user-images.githubusercontent.com/25725313/72218925-7f255e80-3551-11ea-8d66-de82c12d5d79.png)
Координаты местоположения не в градусах/минутах - 5 баллов
115 - 10 = 105 баллов
В работе хорошая адаптивная верстка (не хватает только фиксированной минимальной ширины - при дальнейшем уменьшении ширины экрана ( < 320px) блоки продолжают сжиматься)

**Comment by Victoria-Butrym** [comment]
Thanks for the feedback :)
