### ISSUE TITLE
 [Cross-Check Fancy-Weather] - 'Alex89889'

### ISSUE THREAD

**Issue by Alex89889** [rolling-scopes-school/docs#67]
1) https://alex89889.github.io/fancy-weather/
2)Не реализована возможность голосового поиска по названию населённого пункта – 20 баллов
Не реализован перевод текста страницы (en/ru/be) – 20 баллов
Не реализована возможность переключения единиц измерения температуры – 10 баллов
Итого: - 50 баллов
3) 73

**Comment by Ambrance** [comment]
Ваш максимум: 210 - 50 = 160 баллов
Еще ошибки:
При светлом фоновом изображении совершенно не видно белого текста (проблема решается добавлением text-shadow или добавлением полупрозрачного сплошного фона для блоков с текстом) - 3 балла
![Fancy Weather](https://user-images.githubusercontent.com/25725313/72219440-31abf000-3557-11ea-957e-55c184a43122.png)
При поиске город/страна выводится на русском языке (карта русская тоже) - 2 балла
Время и дата не обновляются - 5 баллов
Карта при поиске не обновляется - 5 баллов
Ошибки в консоли при некорректном запросе поиска - 5 баллов
Итог: 160 - 20 = 140 баллов
