### ISSUE TITLE
[Cross-Check Fancy-Weather] - 'bacila1990'

### ISSUE THREAD

**Issue by bacila1990** [rolling-scopes-school/docs#68]
1) https://nostalgic-dijkstra-95628e.netlify.com
2) Не реализован перевод текста страницы (en/ru/be) – 20 баллов
3) 67

**Comment by Ambrance** [comment]
Ваш максимум: 210 - 20 = 190 баллов
Еще ошибки:
На белом фоне не видно текст белого цвета (лучше добавить тень для текста или полупрозрачный фон для блоков с информацией) - 3 балла
![Document](https://user-images.githubusercontent.com/25725313/72219579-b0555d00-3558-11ea-8648-335ef72e1d3c.png)
Координаты не в градусах/минутах (просто округление до двух знаков после запятой) - 5 баллов
Значение единицы температуры не сохраняется в storage - 5 баллов
Если выполнив поиск попробовать изменить единицы температуры, то меняется не только температура, а все данные. Причем меняется на данные изначального местоположения - 5 баллов
Ошибки в консоли при некорректном поисковом запросе - 5 баллов
Голосовой ввод вместо голосового поиска. Перед тем как нажать кнопку поиска, нужно еще удалить точку из запроса, иначе ошибки в консоли - 5 баллов
Итог: 190 - 28 = 162 балла

**Comment by bacila1990** [comment]
Спасибо за проверку!
