### ISSUE TITLE
[Cross-Check Fancy-Weather] - 'AnzhelaMartsinovich'

### ISSUE THREAD

**Issue by AnzhelaMartsinovich** [rolling-scopes-school/docs#69]
1) Ссылка на диплой вашего проекта
https://martsinovich-anzhela.netlify.com/

2) Оценка в результате самопроверки студентом
Не реализован перевод текста страницы (en/ru/be) – 20 баллов
Присутствуют ошибки в консоли на любом этапе работы приложения – 10 баллов
Итого: 180

3) Балл за cross-check из вашего Score - 165

**Comment by Ambrance** [comment]
Ваш максимум: 210 - 30 = 180 баллов
Еще недочет: 
В переключателе единиц измерения температуры если дважды нажать на кнопку Цельсий или Фаренгейт, всё равно переключается на противоположные единицы измерения, но стили активной кнопки остаются те же (как я поняла классы animate и active должны перемещаться вместе) - 3 балла
В селекте русский язык, хотя приложение полностью на английском (кроме карты)  - 2 балла
Кнопки анимированные - очень красиво.
Итог: 180 - 5 = 175 баллов

**Comment by AnzhelaMartsinovich** [comment]
@Ambrance Спасибо за проверку! Особенно за найденный косяк в изменении температур, так как и сама этого не замечала и другие проверяющие не нашли.
