### ISSUE TITLE
Инструкция для тренеров - "Как стримить лекции на YouTube канал The Rolling Scopes "

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#7]
@davojta Согласился помочь с этим документом
Дедлайн - 1 апреля.

**Comment by Shastel** [comment]
Добавьте пожалуйста в док, что желательно вставлять в ютуб описание лекции, с нужными ссылками (+ включающий в себя дефолтовый шаблон ссылок на соц сетки), и по возможности еще и подготовить теги

**Comment by dzmitry-varabei** [comment]
@Shastel очень по делу написал :) Может ты тоже список составишь, где и что брать (шаблоны описаний/заставки/и тд)?

**Comment by Shastel** [comment]
Шаблонов описаний нет, тамбнейлы я сам генерю

**Comment by Shastel** [comment]
Еще надо помнить, что можно ссылаться на другие лекции с канала (до 5 штук), и если лектор такие найдет то их можно добавить как аннотации либо попросить меня в формате timecode url

**Comment by davojta** [comment]
а мы можем это как то автоматизировать? не знаешь, есть ли апи к примеру
какое ?

**Comment by davojta** [comment]
@dzmitry-varabei сделал базовую инструкцию - https://github.com/rolling-scopes-school/docs/pull/12

Если надо еще чтотот - пиши дополним

**Comment by davojta** [comment]
еще Сергей Шаляпин сказал допишет )

**Comment by davojta** [comment]
@dzmitry-varabei надо закрывать?

**Comment by dzmitry-varabei** [comment]
@davojta да, давай закрывать
