### ISSUE TITLE
[Cross-Check Fancy-Weather] - 'vladimir-drachuk'

### ISSUE THREAD

**Issue by vladimir-drachuk** [rolling-scopes-school/docs#70]
1) Ссылка - https://vladimir-drachuk.github.io/fancy-weather/
2) - есть ошибки при поиске (не продумал согласование API определения местоположения и API прогноза погоды, например при введении в строку слова "Рим" - API местоположения ссылается на итальянский Рим в то время  как прогноз погоды приходит из какого-то российского города) - срабатывает крайне редко, нашел только один город) - 15;
- typeerror в консоли если заходить впервые(при чистом localStorage) - 5;
3) 190;
P.S отправил issue по причине того, что у одного студента не открылось стартовое окно(видимо не убрал баннер рекламы и не сработало API местоположения), из за этого было выставлено только 50% работы.

**Comment by Ambrance** [comment]
Ваш максимум: 210 - 20 = 190
(Еще один город - Брест, меня определили во Францию)
![fancy-weather (2)](https://user-images.githubusercontent.com/25725313/72223482-5a94ab00-3580-11ea-8fc5-bf5b7f365ed9.png)
Еще недочеты:
чуть подпрыгивает контент при смене языка (если убрать height: 100vh у .wrapper, то проблема исчезает; возможно стоит подобрать дополнительно минимальную фиксированную высоту для этого блока) - 2 балла
ошибки в консоли при некорректном поисковом запросе - 5 баллов
почему-то используется свой набор фоновых изображений вместо рандомно генерируемых с unsplash/flickr. Исходя из имен изображений могу предположить, что выбирается в зависимости от сезона, времени суток и погоды. Наверное это лучше в плане релевантности. 
Не нашла в описании задания требований на обязательное использование фотохостингов, а значит снимать баллы не за что.

Итог: 190 - 7 = 183
- очень красивый и продуманный дизайн
- в данных погоды на несколько дней выводится дополнительная информация
- нестандартные иконки
- отличная адаптивность страницы 
Опять же жаль, что за дополнительный функционал по кросс-чеку баллы не добавляются...

**Comment by vladimir-drachuk** [comment]
Спасибо за ревью))
