### ISSUE TITLE
[Cross-Check Fancy-Weather] - 'jetalai3'

### ISSUE THREAD

**Issue by jetalai3** [rolling-scopes-school/docs#71]
1.Ссылка на диплой вашего проекта
https://cranky-carson-5bc711.netlify.com/

2.Верстка только под мобильники -15
Итого 195

3.Балл за cross-check из вашего Score - 162

Один из проверяющих каким-то образом не сумел правильно открыть приложение и поставил 100 баллов из 210 возможных.

**Comment by Ambrance** [comment]
Ваш максимум: 210 - 15 = 195
Еще ошибки:
При загрузке приложения местоположение показывает "Брест, Франция" - 5 баллов
При поиске какой бы запрос не написала в белорусский Брест попасть так и не удалось - всё равно Франция (но если присмотреться, то на секунду всё же показывает Беларусь - 3 балла
Ошибки в консоли при отправке пустой строки в поиск - 5 баллов
В запросе на изображение не учитывается погода - 5 баллов
При переводе температур переводятся отличные от изначально изображенных значений (в случае с Брестом) - 5 баллов
Голосовой поиск срабатывает однократно - 5 баллов
Итог: 195 - 28 = 167 баллов

**Comment by jetalai3** [comment]
В запросе на изображение не учитывается погода - 5 баллов
Погода в запросе учитывается.
http://prntscr.com/qnutxl

**Comment by Ambrance** [comment]
![Снимок экрана от 2020-01-15 12-58-21](https://user-images.githubusercontent.com/25725313/72424446-129ba100-3797-11ea-9894-5b5a6f1bdb9f.png)
При загрузке приложения не учитывается*
