### ISSUE TITLE
Добавить к "Требования к оформлению коммитов и PR" конкретные примеры

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/docs#8]
Из фидбека:
```
Пожалуйста, добавьте в "Требования к оформлению коммитов и PR" 
конкретные примеры, какие типы коммитов использовать в каких случаях,
 а то пока непонятно: добавка кода в HTML - это feat или что?
 Добавление в css (или изменение в css) - это feat, style или fix? 
Добавление или изменение файлов с изображениями или шрифтами - это какой тип? 
Очень нужны примеры! Спасибо!
```

[Требования к выполнению тасков в RSSchool stage#2](https://github.com/rolling-scopes-school/docs/blob/master/stage2-tasks-requirements.md)

**Comment by feugenix** [comment]
А может вообще уменьшить разрешённые типы коммитов к двум: feat и fix? Потому что сильно формализированная система требований к названиям коммитов может сильно путать и пугать людей.
Да и не всегда получается правильно дробить коммиты так, чтобы можно было корректно выбрать тип коммита. Например, у меня идёт процесс рефакторинга кода с написанием документации. Это refactor или docs? Или мне надо искусственно себя заставлять сначала рефакторинг, а потом, в другом коммите писать документацию.

**Comment by davojta** [comment]
@dzmitry-varabei https://github.com/rolling-scopes-school/docs/pull/13
